title: Daily Vibes
email: dailyvibesapp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  iOS app that will aid you in taking control of your life, one day at time through specific and measurable goals
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dailyvibesapp
#github_username:
google_analytics: UA-112407367-1

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .ruby-version
  - scripts
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
